//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoClase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parqueo
    {
        public int Idregistro { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int horaentrada { get; set; }
        public int horasalida { get; set; }
        public int Usuarioid { get; set; }
        public int facturaid { get; set; }
        public int vehiculoid { get; set; }
    
        public virtual Registro Registro { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
